# site settings
title: Kat Lande
subtitle: Bioinformatics
email: kathryn.lande@mail.mcgill.ca
#description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
description: No more stressing over big data.
baseurl: "/me" # the subpath of your site, e.g. /blog
url: "https://katlande.github.io" #the base hostname & protocol for your site
author:
#street_address: 1234 Somewhere Road
city: Vancouver
state: BC
#zip_code: 55555
country: Canada
#phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/katlande
  GitLab:
 # Google-Plus: https://plus.google.com/u/0/+AndrewBanchich
  #Instagram:
  LinkedIn: https://www.linkedin.com/in/kat-lande
  #Twitter: https://twitter.com/andrewbanchich
  #Facebook:
  #Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
